// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10qaH5vs6gK2x1PXCvV3Y4BVGaJw1EJ8',
    appId: '1:711650430443:web:ec234e2e386cd66d0a5dae',
    messagingSenderId: '711650430443',
    projectId: 'instagram-clone-23037',
    authDomain: 'instagram-clone-23037.firebaseapp.com',
    storageBucket: 'instagram-clone-23037.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIGMY4CS3FqkS7qa5jczPEahpDGLBxsMs',
    appId: '1:711650430443:android:f12a53087521c0900a5dae',
    messagingSenderId: '711650430443',
    projectId: 'instagram-clone-23037',
    storageBucket: 'instagram-clone-23037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-eNAwjSQUXBwuxRazHAtZzNaPB57Qi0',
    appId: '1:711650430443:ios:d09ef1eb59e2391d0a5dae',
    messagingSenderId: '711650430443',
    projectId: 'instagram-clone-23037',
    storageBucket: 'instagram-clone-23037.appspot.com',
    iosClientId: '711650430443-ts3vcmkmnk2fo3gn6r4snspb232cv7i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
